### ISSUE TITLE
Changes are not being applied to container

### ISSUE THREAD

**Issue by Hoffmano** [apogiatzis/docker-compose-livereloader#17]
When I change some file the live reloader are triggered, but the change isn't applied

![image](https://user-images.githubusercontent.com/30511353/153663081-e998c5de-f1e6-4225-9fd6-c2b5d6a7a639.png)

Am I commiting any mistake?

**Dockerfile**
```
FROM public.ecr.aws/lambda/python:3.8 as build

RUN yum install -y unzip && \
  curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/98.0.4758.80/chromedriver_linux64.zip" && \
  curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F950363%2Fchrome-linux.zip?alt=media" && \
  unzip /tmp/chromedriver.zip -d /opt/ && \
  unzip /tmp/chrome-linux.zip -d /opt/

FROM public.ecr.aws/lambda/python:3.8

RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib \
  libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
  libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
  xorg-x11-xauth dbus-glib dbus-glib-devel -y
RUN pip install selenium

COPY --from=build /opt/chrome-linux /opt/chrome
COPY --from=build /opt/chromedriver /opt/
COPY app.py ./

CMD ["app.handler"]
```

**docker-compse.yml**
```yml
version: '3'

services:
  web:
    build: .
    working_dir: "/code"
    volumes:
      - ".:/code"
    ports:
      - "8080:8080"
```

**docker-compose-with-reloading.yml**
```yml
version: '3'

services:
  web:
    container_name: web
    build: .

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_CONTAINER=web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/code"

```
