### ISSUE TITLE
livereloader     | Traceback (most recent call last):

### ISSUE THREAD

**Issue by sachithmuhandiram** [apogiatzis/docker-compose-livereloader#3]
I have tried to follow your guide given in [here](https://medium.com/better-programming/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39).

This is my `docker-compose` file.
```
version: '3'

services:
  testserver:
    image: testserver
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1.5              # seconds
      - RELOAD_CONTAINER=test-container-name
```

When I run `sudo docker-compose up --build`, I get following error:

> livereloader     | Traceback (most recent call last):
> livereloader     |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
> livereloader     |     chunked=chunked,
> livereloader     |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
> livereloader     |     conn.request(method, url, **httplib_request_kw)
> livereloader     |   File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
> livereloader     |     self._send_request(method, url, body, headers, encode_chunked)
> livereloader     |   File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
> livereloader     |     self.endheaders(body, encode_chunked=encode_chunked)
> livereloader     |   File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
> livereloader     |     self._send_output(message_body, encode_chunked=encode_chunked)
> livereloader     |   File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
> livereloader     |     self.send(msg)
> livereloader     |   File "/usr/local/lib/python3.7/http/client.py", line 966, in send
> livereloader     |     self.connect()
> livereloader     |   File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
> livereloader     |     sock.connect(self.unix_socket)
> livereloader     | FileNotFoundError: [Errno 2] No such file or directory

OS : Ubuntu 20.04
