### ISSUE TITLE
Not working on Windows hosts.

### ISSUE THREAD

**Issue by patricknelson** [apogiatzis/docker-compose-livereloader#6]
I noticed that this wasn't working at all in Windows (see `docker-compose.yml` config below). When editing the file on the host machine, nothing happens, however if you manually update the file modification timestamp from within the container, it works fine, e.g.

```
# SSH into livereloader
docker-compose exec livereloader bash

# Manually update the file modification timestamp
touch /dev-sync/file.txt
```

I'm not a Python developer, but I _believe_ this may have to do with how Python's `Observer` watches for changes. For example, my node.js containers work perfectly fine for file watching but for some reason this project's file watcher does not. Here's my `docker-compose.yml`. 

```yml
version: '3'
services:
  proxy:
    container_name: proxy # Necessary for livereloader below.
    build: .
    ports: # host:container
      - "80:8080"
    restart: always
    volumes:
      - ./files:/dev-sync

  livereloader:
    container_name: livereloader
    image: apogiatzis/livereloading
    privileged: true
    environment:
      - RELOAD_DELAY=1.5
      - RELOAD_CONTAINER=proxy
      - RELOAD_DIR=/dev-sync/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files:/dev-sync
```

The details of my docker configuration are: 

```
Docker version 19.03.1, build 74b1e89e8a
docker-machine version 0.16.1, build cce350d7 (i.e. Docker Toolbox)
VirtualBox 5.2.32
```
